959: hide market order type
compolabs/spark-frontend pull request #30
Opened 2024-04-22 12:23 UTC by nadiia-balaian

<img width="292" alt="Screenshot 2024-04-22 at 13 22 44" src="https://github.com/compolabs/spark-frontend/assets/109521832/685d88a0-3f66-4bf2-8136-e0a394f6daf8">

2024-04-22 14:20 UTC, lzhabo requested changes

2024-04-22 14:20 UTC, lzhabo commented on src/screens/TradeScreen/RightBlock/CreateOrder/CreateOrder.tsx
> +            <Text>Order type</Text>
давай просто оставим как есть селект, и сделаем дизейбл ORDER_TYPE.Market в конфиге

2024-04-23 08:56 UTC, nadiia-balaian commented on src/screens/TradeScreen/RightBlock/CreateOrder/CreateOrder.tsx
> +            <Text>Order type</Text>
done

2024-04-23 13:54 UTC, lzhabo requested changes

2024-04-23 13:54 UTC, lzhabo commented on src/screens/TradeScreen/RightBlock/CreateOrder/CreateOrder.tsx
> +const StyledInput = styled(Input)`
его нужно убрать, он не используется

2024-04-23 16:55 UTC, lzhabo approved these changes

2024-04-23 16:55 UTC, merged